# Generated by Django 6.0.3 on 2026-03-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. temple, fort, museum', max_length=100, unique=True)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='content.category'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='content.location'),
        ),
    ]
